### ISSUE TITLE
建议使用较为端正、肉眼易于辨别的字体作为字幕的正文字体

### ISSUE THREAD

**Issue by wefriend** [asdfjjkl123/hyakuhuyu-practise#1]
在看《为了在异世界也能抚摸毛茸茸而努力》，发现正文用了华康娃娃体。哎哟，虽说字体可爱，但是东倒西歪的，字体间距又大，笔画又细，看着难受，观看体验不好。

建议使用较为端正、肉眼易于辨别的字体作为字幕的正文字体。
OPED、屏幕字等不重要的字幕用花俏一些的字体也没有关系，而且那部分字幕一般显示的时间比较长，一般有足够时间去辨别思考。
但是正文却不同，显示的时间有长有短。东倒西歪、太过花俏的字体会让人辨认时间过长，脑子要一直在辨别，看着也辛苦。

建议使用圆体、黑体、宋体、楷体、颜体等端正的字体作为正文字体，这种字体不需要太费脑子去辨别是什么字，看着比较舒心。
想花俏一点的，方正少儿、华康手札体、方正达利体、方正FW轻吟体等还不错，这些看上去有点花俏同时还是比较端正的，易于辨别。
但那些过于狂草的、歪歪扭扭的字体，就不建议使用了。
字体间距过大的字体，也不建议使用。虽说aegisub不会因用啥字体而使“字/秒”列变化，但实际那些字体会使字幕的长度变长，肉眼从左往右把一行字幕扫描完的用时就会增加。所以间距太宽的字体观看体验也不太好。

**Comment by asdfjjkl123** [comment]
感谢你的建议,组员相商讨论后,考虑到该作品类型,画风,声优的配音方式,以及你的建议后,我们决定维持使用华康娃娃体. 对于字体风格令你的观感下降,希望你见谅.

以下是我们对你建议的字体作出的评价:
方正少儿, 方正达利, 方正FW轻吟: 这些字体对繁体中文的支持程度不足以用于制作繁体中文正文字幕
华康手札体: 这也是我们当初选择字体时的其中一个后选字体,但后期制作人员希望使用较为花俏的字体,我们亦尊重相关人员的选择

以下是一些建议:
假如你希望将正文字体更换成其他字体,可以使用一些文本编辑软件(如:notepad++),它们有同时在多个文件中取代文字的功能.
寻找的字符为: DFWaWaW5-A
替换字符为: 你希望使用的字体,如华康手札体W5-A
